name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/TshineZheng/EventBusAuto

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  event_bus: ^2.0.0
  event_bus_auto:

dependency_overrides:
  event_bus_auto:
    path: ../event_bus_auto

dev_dependencies:
  build_runner: 
  event_bus_auto_codegen:
    path: ../event_bus_auto_codegen